{
 "title": "Correction Tabelau de bord cluster k8s",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Surveillance VM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Utilisation CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (id)( rate(container_cpu_usage_seconds_total[1m] ) )) / count(node_cpu_seconds_total{mode=\"system\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation système de fichier",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (node_filesystem_size_bytes - node_filesystem_free_bytes) / sum(node_filesystem_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation mémoire",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de conteneurs en fonctionnement",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trafic réseau sur le noeud",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes:rate:sum",
     "legendFormat": "RECEIVE"
    },
    {
     "expr": "- instance:node_network_transmit_bytes:rate:sum",
     "legendFormat": "TRANSMIT"
    }
   ]
  },
  { "title": "Conteneurs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Trafic sortant par conteneur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "instance:node_network_transmit_bytes:rate:sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trafic entrant par conteneur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes:rate:sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM par conteneur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(container_memory_rss{}) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU par conteneur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by(id) (rate(container_cpu_usage_seconds_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}