{
 "title": "[PROJ-1][Dev]Conteneurs App Laravel",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "containername", "query": { "query": "label_values(name)" } }
  ]
 },
 "panels": [
  {
   "title": "Nombre de conteneurs up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\"shouts-laravel.*\"}[30m])) "
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU par Conteneur",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"shouts-laravel.*\"}[1m])) by (name) * 100"
    }
   ]
  },
  {
   "title": "RAM par conteneur",
   "type": "timeseries",
   "description": "Affichage de l'utilisation de la RAM par conteneur pour mon application",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"$containername\"}) by (name)"
    }
   ]
  }
 ]
}