{
 "title": "Monitoring Application Kingoludo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Panel Title", "type": "grafana-clock-panel", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 0 },
   "format": "percent",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100 "
    }
   ]
  },
  { "title": "VM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Trafic réseau VM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[5m])) by (host)",
     "legendFormat": "RECEIVE"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[5m])) by (id)",
     "legendFormat": "TRANSMIT"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Ram par conteneur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\".*\",name=~\".*\",name=~\".+\"}) by (name)"
    }
   ]
  },
  { "title": "Réseaux", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Trafic Réseau sortant par conteneur",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\".*\",name=~\".*\",name=~\".+\"}[5m])) by (name)"
    }
   ]
  },
  {
   "title": "Trafic entrant par conteneur",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\".*\",name=~\".*\",name=~\".+\"}[5m])) by (name)    "
    }
   ]
  }
 ]
}