version: "3.8"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescale
    shm_size: 4g
    hostname: timescaledb
    restart: always
    ports:
      - ${TIMESCALEDB_PORT}:5432
    volumes:
      - myapp:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${TIMESCALEDB_PASSWORD}
      POSTGRES_USER: ${TIMESCALEDB_USER}
      POSTGRES_DB: ${TIMESCALEDB_DB}
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    depends_on:
      - timescaledb
    ports:
      - 3030:3000
    environment: 
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: timescaledb:5432
      GF_DATABASE_NAME: timescale_database
      GF_DATABASE_USER: timescale
      GF_DATABASE_PASSWORD: timescaledb
      GF_DATABASE_SSL_MODE: disable
volumes:
  myapp: