{
 "title": "Etat de chaque service",
 "description": "Vue globale des services",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "service", "query": "probe_success" }
  ]
 },
 "panels": [
  {
   "title": "Service internet",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{source=\"internet\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Taux de disponibilité",
   "type": "singlestat",
   "description": "Moyenne de la disponibilité sur la période",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "probe_success{source=\"internet\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "historique",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{source=\"internet\", service=\"$service\"} == 1"
    }
   ]
  },
  {
   "title": "Tendance instantanée",
   "type": "stat",
   "description": "dernière variation de la disponibilté horaire",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deriv(service:dispoHoraire{service=\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "Tendance sur la période",
   "type": "stat",
   "description": "Variation de la disponibilté horaire sur la période",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "deriv(service:dispoHoraire{service=\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "Evolution taux de disponibilité horaire",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "service:dispoHoraire{source=\"internet\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Temps de réponse",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{source=\"internet\",service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Mémoire utilisée",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_project=\"$service\", instance=\"192.168.122.30:9200\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Service infra",
   "type": "singlestat",
   "description": "Test l'accès HTTP depuis l'infra",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "probe_success{service=\"$service\",source=\"infra\"} == 1"
    }
   ]
  },
  {
   "title": "Temps de réponse",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{source=\"infra\",job=\"services depuis infra\",service=\"$service\"} "
    }
   ]
  },
  {
   "title": "Liaison infra",
   "type": "singlestat",
   "description": "Test la connexion TCP depuis l'infra",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "probe_success{service=\"$service\",source=\"nfra\"} == 1"
    }
   ]
  },
  {
   "title": "Temps de réponse",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{source=\"infra\",job=\"connection depuis infra\",service=\"$service\"} "
    }
   ]
  },
  {
   "title": "Service production",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 38 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "probe_success{service=\"$service\", source=\"production\"} == 1"
    }
   ]
  },
  {
   "title": "Temps de réponse",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{source=\"production\",job=\"services depuis production\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Liaison production",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 43 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "probe_success{service=\"$service\", source=\"cproduction\"} == 1"
    }
   ]
  },
  {
   "title": "Temps de réponse",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{source=\"production\",job=\"connection depuis production\",service=\"$service\"}"
    }
   ]
  }
 ]
}