{
 "title": "Logs",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "container_name", "label": "Service", "query": "label_values(container)" },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "query" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container_name\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{container=\"$container_name\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "title": "Total count of stderr / stdout pie",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({service=\"$container_name\"})[$__interval])) by (host)"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" donut",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (container)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({container=\"$container_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" historical",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (container)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate per Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(({container=\"$container_name\"} |~ \"(?i)$searchable_pattern\")[30s])) by (container)"
    }
   ]
  },
  {
   "title": "Count of stderr / stdout historical",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container_name\"})[$__interval])) by (stream)"
    }
   ]
  }
 ]
}