{
 "title": "Logs système",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "varlog",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"}"
    }
   ]
  },
  {
   "title": " echec d'authenfication dans les 5 minutes",
   "type": "graph",
   "description": "Donne une idées des tentatives d'intrusions",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"varlogs\"} |= \"pam_unix(sshd:auth): authentication failure\" [$__interval])"
    }
   ]
  },
  {
   "title": "échecs d'authenfication",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"varlogs\"} |= \"pam_unix(sshd:auth): authentication failure\" [$__interval])"
    }
   ]
  },
  {
   "title": "moyenne  echec d'authenfication",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"varlogs\"} |= \"pam_unix(sshd:auth): authentication failure\" [$__interval])"
    }
   ]
  },
  {
   "title": "Total  echec d'authenfication",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"varlogs\"} |= \"pam_unix(sshd:auth): authentication failure\" [$__interval])"
    }
   ]
  },
  {
   "title": "Apache http",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/apache2/access.log\"}"
    }
   ]
  },
  {
   "title": "Apache https",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/apache2/ssl_access.log\"}"
    }
   ]
  },
  {
   "title": "Googlebot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count_over_time({filename=\"/var/log/apache2/ssl_access.log\"} |= \"Googlebot)\" [$__interval])"
    }
   ]
  },
  {
   "title": "bingbot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count_over_time({filename=\"/var/log/apache2/ssl_access.log\"} |= \"bingbot)\" [$__interval])"
    }
   ]
  },
  {
   "title": " SemrushBot/6~bl",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count_over_time({filename=\"/var/log/apache2/ssl_access.log\"} |= \"SemrushBot/6~bl\" [$__interval])"
    }
   ]
  },
  {
   "title": "AhrefsBot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({filename=\"/var/log/apache2/ssl_access.log\"} |= \"AhrefsBot/6.1; +http://ahrefs.com/robot/)\" [$__interval])"
    }
   ]
  },
  {
   "title": "Baiduspider",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count_over_time({filename=\"/var/log/apache2/ssl_access.log\"} |= \"Baiduspider\" [$__interval])"
    }
   ]
  },
  {
   "title": "YandexBot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count_over_time({filename=\"/var/log/apache2/ssl_access.log\"} |= \"YandexBot\" [$__interval])"
    }
   ]
  },
  {
   "title": "opensiteexplorer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count_over_time({filename=\"/var/log/apache2/ssl_access.log\"} |= \"(compatible; DotBot/1.1; http://www.opensiteexplorer.org/dotbot, help@moz.com)\" [$__interval])"
    }
   ]
  }
 ]
}