{
 "title": "Surveillance KingoLudo",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "conteneur", "label": "Conteneur", "query": { "query": "label_values(name)" } }
  ]
 },
 "panels": [
  { "title": "VM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nombre de conteneurs en fonctionnement",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Utilisation système de fichier",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes - container_fs_usage_bytes) / sum(container_fs_limit_bytes)"
    }
   ]
  },
  {
   "title": "Utilisation mémoire",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Utilisation CPU VM",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (container_name)( rate(container_cpu_usage_seconds_total[1m] ) )) / count(node_cpu_seconds_total{mode=\"system\"}) * 100"
    }
   ]
  },
  {
   "title": "Trafic réseau sur le noeud",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[5m])) by (host)",
     "legendFormat": "RECU"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[5m])) by (id)",
     "legendFormat": "SORTANT"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "100 - (avg by (name) (irate(container_cpu_usage_seconds_total[5m])) *100)",
     "legendFormat": "{{name}} | CPU"
    },
    {
     "expr": "sum(100 - ((container_spec_memory_limit_bytes - container_memory_usage_bytes)  * 100 / container_spec_memory_limit_bytes) ) by (name) ",
     "legendFormat": "{{name}} | MemoireRestante"
    }
   ]
  },
  { "title": "Conteneurs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU par conteneur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\".*\",name=~\"$conteneur\",name=~\".+\"}[5m])) by (name) *100"
    }
   ]
  },
  {
   "title": "RAM par conteneur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\".*\",name=~\"$conteneur\",name=~\".+\"}) by (name)"
    }
   ]
  },
  {
   "title": "Trafic réseau entrant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\".*\",name=~\".*\",name=~\".+\"}[5m])) by (name)"
    }
   ]
  },
  {
   "title": "Trafic réseau sortant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\".*\",name=~\".*\",name=~\".+\"}[5m])) by (name)"
    }
   ]
  }
 ]
}