{
 "title": "Vue générale des services",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Etat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{source=\"internet\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Tendance de la disponibilité horaire ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deriv(service:dispoHoraire{source=\"internet\"}[5m])",
     "legendFormat": "{{service }}"
    }
   ]
  },
  {
   "title": "Taux de disponibilité sur la période",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_success{source=\"internet\"}",
     "legendFormat": "{{service }}"
    }
   ]
  },
  {
   "title": "Tendance de la disponibilité horaire  sur la période",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "deriv(service:dispoHoraire{source=\"internet\"}[5m])",
     "legendFormat": "{{service }}"
    }
   ]
  },
  {
   "title": "Evolution taux de disponibilité  horaire",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "service:dispoHoraire", "legendFormat": "{{service }}" }
   ]
  },
  {
   "title": "Temps de réponse",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{source=\"internet\"}",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}